### ISSUE TITLE
Service does not exist in Symfony2

### ISSUE THREAD

**Issue by ethought** [OpenBuildings/postmark#31]
The service definition "swiftmailer.mailer.transport.swift_transport.postmark" does not exist.

Any ideas how to fix this?

**Comment by hkdobrev** [comment]
@ethought I think you should use the [SwiftmailerBundle for Symfony](https://symfony.com/doc/master/reference/configuration/swiftmailer.html#transport).

**Comment by ethought** [comment]
I need Postmark transport though.

**Comment by sprain** [comment]
The SwiftmailerBundle actually expects your service name prefixed with `swiftmailer.mailer.transport`

So your service config should look like this:

```
services:
    swiftmailer.mailer.transport.postmark:
        class: Openbuildings\Postmark\Swift_PostmarkTransport
        arguments:
            - POSTMARK_API_KEY
```

And in `config.yml`:
```
swiftmailer:
    transport: postmark
```
